# Generated by Django 4.2.6 on 2024-05-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_debitnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='reference_no',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
